#ifndef RT_ENGINE_ERRORS_H
#define RT_ENGINE_ERRORS_H

enum RT_engine_error {ENGINE_ERROR_OK, ENGINE_ERROR_INIT_FAILED, ENGINE_ERROR_BAD_ALLOC,
                      ENGINE_ERROR_FAILED,ENGINE_ERROR_BAD_VALUE};

#endif // RT_ENGINE_ERRORS_H
